services:
  - type: web
    name: progress-tracker
    env: docker               # <--- CHANGED THIS from 'php' to 'docker'
    startCommand: ""          # Dockerfile handles the start command now
    envVars:
      - key: APP_NAME
        value: Progress_Tracker
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: progress-tracker-db
          property: connectionString

databases:
  - name: progress-tracker-db
    databaseName: progress_tracker
    user: progress_user
    plan: free